name: Cryptone V11

on:
  workflow_dispatch:

jobs:

  bot:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r requirements.txt

      - run: |
          python main.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
